### ISSUE TITLE
Create single content section in Elements website

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#100]
## What

Create a "content" section that can house multiple single-page guides, to replace the brand-specific content sections that exist today e.g. https://elements.springernature.com/nature/content

## Why

Our content guidance is not brand specific - it generally applies to all brands, so this helps us reduce duplication.

We also need to update our content guidance, so this gives us a good excuse to do that.

## Done when

- [x] Content sections have been removed from the brand sections (Perhaps keeping the Nature content somewhere in an archive if possible, so we can refer to it if we need it)
- [x] Elements.springernature.com/content section has been created, with a landing / introduction page
- [x] A-Z styleguide has been added
- [x] Content section is linked to from the main navigation
- [x] Styleguide is published
- [x] Content review by Alex

## Anything else?

The first piece of content published will be the new A-Z styleguide which has been worked on by Gaynor Burns.

**Comment by sturobson** [comment]
> Perhaps keeping the Nature content somewhere in an archive if possible, so we can refer to it if we need it

I'm not currently planning on removing the `/content/` folder for brands so nature's content [can still be found here](https://github.com/springernature/ux-elements-docs/tree/main/nature/content). Is that ok?

**Comment by amyhupe** [comment]
@amyhupe to send draft A-Z styleguide and introduction page content so @sturobson can generate previews to check with Gaynor

**Comment by sturobson** [comment]
![Screen Shot 2022-12-05 at 12 48 55](https://user-images.githubusercontent.com/925197/205669916-c7e593bf-2f54-4bc3-90a8-ee87480d1197.png)

**Comment by sturobson** [comment]
![Screenshot 2022-12-05 at 14 51 21](https://user-images.githubusercontent.com/925197/205670007-403817b3-dfa4-4999-9338-e8adfe39147c.jpg)
