### ISSUE TITLE
Update "style guide" across Elements site

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#105]
## What

We are using a mixture of "style guide" (as two words) and "styleguide" (as one word) across the Elements website. 

After discussing with the team, we agreed to standardise all instances to "style guide" (two words).

## Why

To make things consistent, as good design system teams should :)

## Done when
- [ ] All instances have been identified and updated

## Anything else

We probably need to run a search in all of our repos for the term, to find all instances, but the places we know need updating are:

- [Nature styleguide title, url and intro content](https://elements.springernature.com/nature/styleguide)
- [Springer styleguide title, url and intro content](https://elements.springernature.com/springer/styleguide)
- [Springer Nature styleguide title, url and intro content](https://elements.springernature.com/springernature/styleguide)

**Comment by Sreilys** [comment]
I would need a list of "all of our repos". As of today I know /frontend-toolkits, /frontend-design-system.
Which one am I missing? 
Thx

**Comment by amyhupe** [comment]
> I would need a list of "all of our repos". As of today I know /frontend-toolkits (nothing to change), /frontend-design-system (nothing to change). Which one am I missing? Thx

@Sreilys - we also have /ux-elements-docs
