### ISSUE TITLE
UX Documentation - global-forms

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#12]
### What

The new Global forms component has been released and includes some technical documentation:
https://elements.springernature.com/springernature/components/global-forms

Content review and improvements of documentation

### Why

The documentation needs design guidance on when to use each form element and how they work from a UX perspective.

### Done when

- [x] Improvements with design guidance is made
- [x] Updates have been reviewed by content designer (Lexi)
- [x] Updates have been reviewed by Elements team
- [x] Content in examples reviewed in content crit
- [x] Updates published

### Google doc:

https://docs.google.com/document/d/1lci7bQvnJK5zeOKGHliplf5krIA3FytR8YSHXURNSsM/edit#heading=h.f5a9lz1gz0yw

**Comment by sturobson** [comment]
So, @Heydon has been working on forms for the new MVP/MLP for springer.com and has used the springer nature forms as the springboard. 

I've discussed this week that now two brands are using the same form HTML structures - perhaps it's a good idea to move towards a 'global forms' package. 

I've volunteered to take this on as Heydon continues with the new springer.com MVP/MLP. 

I need to create an issue in the frontend-toolkits that similarly reflects this.

**Comment by foxintherain** [comment]
@sturobson @alexkilgour @morgaan @amyhupe I am almost finished with the [new forms design](https://www.sketch.com/s/c77d316e-76e5-403e-95b8-93021fc6c95e/p/0EB75A8C-3CC3-40C8-A48E-AE685CB267BC), would this be a good time to have a catch up call?

**Comment by foxintherain** [comment]
PR now in review: https://github.com/springernature/frontend-toolkits/pull/857

**Comment by foxintherain** [comment]
This has now been updated to the next version: https://github.com/springernature/frontend-toolkits/pull/862
