### ISSUE TITLE
Update Springer Nature footer content

### ISSUE THREAD

**Issue by fred-warburton** [springernature/ux-elements-docs#134]
### What
Update footer component Elements documentation and communicate changes to users

### Why
The purpose of this task is to ensure that the footer component Elements documentation is up to date. Additionally, it is necessary to communicate to users who are using this component that they need to update their footers accordingly. This will maintain consistency and compliance with the new standards.

### Done when

- [ ] Change the link to the CMP from "Manage Cookies/Do Not Sell My Data" to "Your privacy choices/Manage cookies". 

- [ ] Change the link for "Your privacy choices/Manage cookies" to the newly updated CPRA statement: https://www.springernature.com/gp/legal/ccpa

- [ ] Change the link text from "California Privacy Statement" to "Your US state privacy rights".

- [ ] Communicate the changes to users who are using the footer component, emphasising the need to update their footers to the latest version of elements. @ricky-lau 

### Anything else
Please ensure the following:

Contact Quinton Creighton to confirm if the provided changes align with the new standard wording.

**Comment by ricky-lau** [comment]
> Change the link for "Your privacy choices/Manage cookies" to the newly updated CPRA statement: https://www.springernature.com/gp/legal/ccpa

The link should be on `Your US state privacy rights` and `Your privacy choices/Manage cookies` should initiate the consumer's cookie consent management tool.
