### ISSUE TITLE
Document the Nature Header

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#38]
## What

Create design and technical guidance for the Nature header. 

## Why

We need to provide design and technical guidance to help Elements users understand when and how to use components.

We are prioritising Nature components in the first instance as part of [our next milestone](https://docs.google.com/document/d/1BayW8N5HLk9Xf63dqg4w4uwP7shbFGwwJF3omRmDBqY/edit#heading=h.303kx2l9n951) (in Feb 2022) to move Elements towards an organisation-wide launch.

## Done when

- [x] Component documentation is drafted
- [x] Reviewed by a designer
- [x] Reviewed by a developer
- [x] Documentation is published in Elements website

## Anything else

We need to include a visual example of the component as part of the documentation.

Ideally, this will be a live demo like the ones used for Springer components ([example here](https://frontend-design-system.private.springernature.app/springer/components/springer-header). If we can't get that working in time, we should go ahead with a screen shot until that's available.

### Links

- [Live documentation (doesn't include design guidance at the moment)](https://frontend-design-system.private.springernature.app/nature/components/nature-header)
- [Draft documentation update](https://docs.google.com/document/d/1mr_ePfwli2pvHCntCImdfGkKcwGDLxqF6do287HkEYw/edit)

**Comment by foxintherain** [comment]
![image](https://user-images.githubusercontent.com/15365576/144214486-083ea5e7-3700-4884-a7aa-fb40b4ef47e7.png)

**Comment by foxintherain** [comment]
- Have agreed primary navigation is part of the header component with @alexkilgour & @amyhupe

**Comment by amyhupe** [comment]
Pull request: https://github.com/springernature/frontend-toolkits/pull/661
