### ISSUE TITLE
New design for Nature Sort By

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#40]
## What

Design a new approach to the Nature Sort By component.

## Why

The existing design unnecessarily relies on javascript and could be simplified. This will also help products to be more accessible.

## Done when

- [x] Visual mockup is made
- [x] Reviewed by a developer
- [x] Reviewed by Amy

**Comment by foxintherain** [comment]
@benjclark  See new design for Sory-By below, as we discussed:

![1 wide-search](https://user-images.githubusercontent.com/15365576/145007028-1a9845a9-f1dd-409d-a8cb-2c174490ee44.png)

**Comment by foxintherain** [comment]
@amyhupe @benjclark this might be part of the documentation but not sure if we want to come up with a limit on how many options can be used in the sort by? e.g. if we exceeded 5 options, it might be better to use a dropdown menu

**Comment by foxintherain** [comment]
Mobile:
![2 mobile-search](https://user-images.githubusercontent.com/15365576/145804972-e61ecd8a-c310-457e-9a96-da0b9900e4fb.png)

**Comment by foxintherain** [comment]
Pandora have now created a jira ticket to update this: https://jira.springernature.com/browse/PAN-1598

**Comment by amyhupe** [comment]
Hi James, 

This looks good. My only comments are about the wording of the sort by date radio labels.

1. We should say what the date represents. For example, is it Date published? Date updated? It might be worth including this point in the guidance, too.

2. If we're going to say "oldest first" then for consistency I think we should also say "most recent first". If that makes the label length feel clunky and uneven, you could try:

- Date updated (new to old)
- Date updated (old to new)

What do you think?

I'm aware we'll want people to decide the exact for themselves depending on what options they offer but I feel we should lead by example.

**Comment by foxintherain** [comment]
>     1. We should say what the date represents. For example, is it Date published? Date updated? It might be worth including this point in the guidance, too.

That makes sense, would we we also want to change the date filter above to "Date published" so this is consistent?

>     2. If we're going to say "oldest first" then for consistency I think we should also say "most recent first". If that makes the label length feel clunky and uneven, you could try:

>     * Date updated (new to old)
>
>     * Date updated (old to new)

Yes this reads better. Will update the design and check with Rosario (UX for Pandora) that "Date published" is the correct term.

**Comment by amyhupe** [comment]
> That makes sense, would we we also want to change the date filter above to "Date published" so this is consistent?

Yes I think so!

**Comment by foxintherain** [comment]
@amyhupe Have check with Rosario and we can use "Date published" as the label.

Updated design:
![Group 3](https://user-images.githubusercontent.com/15365576/146551082-88278723-9b1d-457c-8d15-7bb2d43567a8.png)

![Sort by](https://user-images.githubusercontent.com/15365576/146551106-bd5bbd91-9294-4685-ae79-db0da771adef.png)
