### ISSUE TITLE
Create component docs research task and discussion guide

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#50]
### What

Create a task and discussion guide for upcoming usability testing of component documentation.

### Why

We've recently changed our approach to writing component documentation to include both:

- design guidelines
- developer documentation

Our approach was based on research into what our users need from component docs. 

We now want to test some of the new documentation to check our approach is working and meets needs.

### Done when

- [x] Discussion guide drafted
- [x] Checked by Amy
- [x] Checked by Steph (Research Ops lead)

### Anything else

- [Findings from previous research](https://docs.google.com/document/d/1-3ztiXGActq2inuTbdD0x8NyPThdoib93gBb9FWDtd8/edit) 
- [Research brief](https://docs.google.com/document/d/1vn8GcGsDgLcG5kREBjUhESDxXcxnmLIjbddv2UYz7nY/edit)

**Comment by foxintherain** [comment]
Started a draft on the discussion guide: https://docs.google.com/document/d/177bPZ9qkVpZn9o-RRfVUxePTWNfmV4NgZY52YO1q3XA/edit#heading=h.4dj5bjie8ggj

**Comment by amyhupe** [comment]
@foxintherain I've reviewed the draft and left some comments for you to take a look at.
