### ISSUE TITLE
Give Elements docs pages unique page titles

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#54]
### What

Review and update page <titles> in Elements website to make sure each page has a unique <title>.

### Why

At the moment, the Elements site has a number of duplicated <titles> - for example "Patterns: Elements" is the <title> for Patterns landing pages on all 3 brands.

Having unique <title>s is important for SEO and accessibility.

### Done when

- [ ] Duplicate tags identified
- [ ] Convention established for <titles>
- [ ] Titles updated

### Anything else

[Content audit started](https://docs.google.com/spreadsheets/d/1U9D-e7jbqpWTtGqfmKzBWmkhQSPNb8M5ekGFrhlZOow/edit#gid=0) - which shows some of the pages with duplicate titles.

**Comment by sturobson** [comment]
this will be part of [the new Elements Documentation Site](https://github.com/springernature/elements/issues/6)
