### ISSUE TITLE
Update heading styles for the Springer brand-context

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#60]
### What
Update the heading styles to ensure a clear visual hierarchy that can be used consistently across all springer sites.

### Why
@Heydon has discovered from working on the new springer.com landing pages that heading styles are being overridden on the[ journal sites](https://www.springer.com/journal/216). This is due to H2's and H1's not having a lot of visual difference.

### Done when

- [x] New heading styles are agreed with UX from SPA team (@foxintherain) 
- [x] Update styles in toolkit (@Heydon) 
- [x] Communicate updates to Pandora team (@foxintherain)

**Comment by foxintherain** [comment]
New typography scale:
![3 typography](https://user-images.githubusercontent.com/15365576/160159382-f5bcac25-6ae2-4509-9b10-1d8f9f20d8f4.png)

![3 typography](https://user-images.githubusercontent.com/15365576/160159427-fbae8d8c-3fa4-4ea6-b968-3dfe4db4d56c.png)

**Comment by amyhupe** [comment]
@heydon - have assigned this to you as we think this should now be ready to update in the toolkit.

**Comment by foxintherain** [comment]
![6 typography](https://user-images.githubusercontent.com/15365576/161846442-629ba111-6222-4ed3-8ecc-7d0096a80452.png)

**Comment by foxintherain** [comment]
Final update:
![6 typography](https://user-images.githubusercontent.com/15365576/162969230-b6300c57-ba8f-4240-a026-45447a0273f4.png)

**Comment by Heydon** [comment]
@amyhupe @foxintherain see https://github.com/springernature/frontend-toolkits/pull/727 for the toolkits changes

**Comment by foxintherain** [comment]
@matteo-gildone @benjclark @ricky-lau Please toolkit changes https://github.com/springernature/frontend-toolkits/pull/727

**Comment by foxintherain** [comment]
FYI @tesstesstess
