### ISSUE TITLE
Work on an engagement plan for elements

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#61]
### What

Think about how we can use our Hive page for comms for stakeholders and other relevant groups at SN, to create awareness of elements, including our official launch.

### Why

To help achieve the goals of elements, we need to build wider awareness in the company of what we’re trying ro do and why its important.

### Done when

- [x] We've identified important stakeholders and relevant channels to reach them through
- [x] We have a plan for regular updates

**Comment by foxintherain** [comment]
Engagement plan for stakeholders and different audiences:
https://docs.google.com/document/d/1S8cwMHIxxKzcdd6b5gs94tBmTDuYkqvOgEolRYjxM84/edit#heading=h.la9dj4ddznb6

**Comment by amyhupe** [comment]
Caught up with @foxintherain on 18/7 to talk about this issue. 

- Have agreed to hold off on any "introducing Elements" posts / comms until we've moved to a single package release, as this will have significant implications for how Elements works. 
- We also agreed to pilot a weeknote for 6 weeks
