### ISSUE TITLE
Update layout of Elements website to give demos more room

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#71]
## What

Update layout of Elements website to give component demos more width so they display a desktop version by default, on desktop.

## Why

At the moment, demos display at tablet width by default. We've seen in user research that this is confusing for some users who are looking for a desktop version of a component. 

We also know this is the most common view for most of our products' users, who most often access journal sites on desktop.

## Done when

- [x] New layout has been designed
- [x] Layout designs have been reviewed by @sturobson and @amyhupe
- [x] New layout has been implemented

## Anything else

[Prototype on sketch (increases max page width to 1240px)](https://www.sketch.com/s/ff5e0b72-6d79-4ea7-bc10-126b557cdec7/p/012C6D1C-A969-4E83-8C47-CAAF6CA2BFBE/canvas)

**Comment by foxintherain** [comment]
![Journey 1 - ai](https://user-images.githubusercontent.com/15365576/164756548-764b5d1b-121b-481a-837f-5fb9c202e1b4.png)

![Rectangle](https://user-images.githubusercontent.com/15365576/164756951-b308bb3b-c5c0-47ba-9cbe-f27b97bfbdd4.png)

**Comment by amyhupe** [comment]
This looks good to me James, thanks. @sturobson any comments from you or could we start work on this?

**Comment by sturobson** [comment]
I did some preliminary fudging in the browser developer tools. I can probably pick this up later today. Shouldn't take too long.

**Comment by sturobson** [comment]
Ah … there is a couple of things … 

- are we going with the style refresh? header background colour change, navigation colour change?
- What happens to "Page Title" 

Or … is this first pass just widening the 'page'?

**Comment by foxintherain** [comment]
I think we can just widen the page for now, and look at the other changes after we've done the prototype testing

**Comment by sturobson** [comment]
before:

![a screenshot of the top part of http://localhost:3000/springer/components/springer-ad showing the header, navigation and part of the content with a width of 1080px](https://user-images.githubusercontent.com/925197/166663675-c1c2569f-7b87-4fc0-910b-f4926ec36f70.png)

after:

![a screenshot of the top part of http://localhost:3000/springer/components/springer-ad showing the header, navigation and part of the content with a width of 1248px](https://user-images.githubusercontent.com/925197/166663884-2f61baff-293c-451d-a1f3-6b3bd4b84f37.png)

**Comment by sturobson** [comment]
before, at 1080px wide:

![a screenshot of the top part of http://localhost:3000/springer/components/springer-ad showing the header, navigation and part of the content with a width of 1080px](https://user-images.githubusercontent.com/925197/166664014-4ef7cc62-6786-4eb1-9f4f-12c10e05d8bc.png)

after, at 1248px wide: 

![a screenshot of the top part of http://localhost:3000/springer/components/springer-ad showing the header, navigation and part of the content with a width of 1248px](https://user-images.githubusercontent.com/925197/166664057-616f3257-04c2-468f-9c44-ee8ded2c4539.png)
