### ISSUE TITLE
Get Colours, Typography and Spacing pages using tokens

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#73]
## What

Update Nature Colours, Typography and Spacing pages to consume design tokens.

## Why

To make the documentation easier to maintain and ensure it's in sync with the source of truth (code).

## Done when

- [ ] Gather examples of tokens docs
- [ ] Elements team reviews examples and decides what's needed for Springer Nature
- [ ] Update pages as agreed to use tokens

**Comment by sturobson** [comment]
We can close this as [it's part of 'the work' involved in the SRS](https://github.com/springernature/frontend-design-system/issues/144)
