### ISSUE TITLE
Implement tabs on codeblocks so users can see handlebars and html

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#74]
## What

Let users switch between .hbs and html when viewing component demo code on the Elements website.

## Why

In recent user research, some users wanted to see html to understand how a component worked and was structured.

Some users used inspector in the Elements website to get this information. Others went to GitHub to look at the component demo.

Letting users see this information in the Elements website means they won't have to travel somewhere else to see it. It also provides better support for teams who aren't using handlebars and may want to use the html as a start point for a component built in their own templating engine.

## Done when

- [ ] Tabs are implemented

**Comment by sturobson** [comment]
this will be part of [the new Elements Documentation Site](https://github.com/springernature/elements/issues/6)
