### ISSUE TITLE
Investigate how to show brand-specific demos for global components depending on where in the Elements site a user is

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#78]
## What

Show users brand-styled demos depending on where they are in the Elements site.

For example, if you're in the Springer section of the Elements site viewing a global card - you'll see a Springer-styled card.

## Why

**Comment by sturobson** [comment]
this will be part of [the new Elements Documentation Site](https://github.com/springernature/elements/issues/6)
