### ISSUE TITLE
Bug with iframe height on load

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#83]
## What

The height of the iframe containing component demos in the Elements Design System website should be set by the contents. This lets users see the whole component without having to resize the iframe. 

Occasionally, the iframe doesn't load correctly, and the iframe loads at a much lower height, obscuring some of the demo.

We should investigate what's causing this and fix the issue.

## Why

We know from user research that component demos provide an important visual confirmation that users have found what they're looking for. This issue means that some users might miss this cue.

## Done when

- [ ] Cause of issue identified
- [ ] Issue fixed
 
## Anything else

So far, the problem has been observed when using MacOS / Chrome

**Comment by sturobson** [comment]
this will be part of [the new Elements Documentation Site](https://github.com/springernature/elements/issues/6)
