### ISSUE TITLE
Audit Nature styleguide documentation

### ISSUE THREAD

**Issue by amyhupe** [springernature/ux-elements-docs#88]
## What

Audit Nature styleguide documentation and summarise what needs:

- removing
- adding
- updating

## Why 

The styleguide documentation was written some time ago and needs bringing up to date.

This is one of our OKRs for 2022.

## Done when:

- [x] Review guidance
- [x] Audit document created 
- [x] Document reviewed with Elements team
- [x] Tasks created and added to board

## Anything else

- https://elements.springernature.com/springernature/styleguide 
- Review a11y page and try to integrate content into other, relevant places

**Comment by foxintherain** [comment]
Audit document: https://docs.google.com/document/d/1xymMjUM3_gIZubGXyW2JryzK3fHVTmwEbi91AmjS9yc/edit
