### ISSUE TITLE
Layout documentation review and update

### ISSUE THREAD

**Issue by foxintherain** [springernature/ux-elements-docs#91]
## What

Content review and improvements of Layout guide for all brands to identify improvements needed or gaps. Uses new structure, as [defined in the styleguide audit](https://github.com/springernature/ux-elements-docs/issues/88).

## Why

Layout documentation was created a while ago and needs updating following the styleguide audit.

## Done when

- [x]   Content has been reviewed
- [x]   Layout Component content has been reviewed
- [x]   Improvements have been made (to Layout guide)
- [x]   Updates have been reviewed by UI design team
- [x]   Updates have been reviewed by Elements team
- [x]   Updates published

## Draft

https://docs.google.com/document/d/14Ks1thJIhcNj_PsxrusK4ZEtlZgI20m42DFteN_wZi8/edit

**Comment by foxintherain** [comment]
### Initial kickoff
Following our catchup last Wednesday, we agreed first for @alexhallspringer review the content for the existing Layout component pages:

- [Grid component](https://elements.springernature.com/springernature/components/global-grid) (to be depreciated)
- [Layout cluster component](https://elements.springernature.com/springernature/components/global-layout-cluster)
- [Layout Grid component](https://elements.springernature.com/springernature/components/global-layout-grid) 
- [Layout Stack component](https://elements.springernature.com/springernature/components/global-layout-stack) 
- [Layout with sidebar component](https://elements.springernature.com/springernature/components/global-layout-with-sidebar)

### Catch up on Tuesday

- The principles behind the layout components (fluid layout, no fixed breakpoints) come from [Every layout](https://every-layout.dev/layouts/sidebar/) @Heydon to write a high level summary of these principles that can be included in the Layout styleguide and then reviewed by @alexhallspringer 
- Investigate creating a subsection for the layout components on the elements website

**Comment by amyhupe** [comment]
We briefly discussed whether it makes sense to keep layouts as components, or whether they should sit at the styles / utilities level. We agreed we would keep them as is and create a layout style guide which sets out principles and links to individual layout component documentation.

**Comment by amyhupe** [comment]
@alexhallspringer to review latest iteration of principles. 

To finish this and publish a version one, @foxintherain need to:

- [ ] create images and text descriptions of common layout types 
- [ ] create image and text description of page anatomy

**Comment by foxintherain** [comment]
Have created a new issue for [Spacing documentation](https://github.com/springernature/ux-elements-docs/issues/122)
